# Generated by Django 4.2.7 on 2025-12-19 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('movement_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movement Record',
                'verbose_name_plural': 'Movement Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PoseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=50)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('z_position', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_data', to='bodyanalytics.movementrecord')),
            ],
            options={
                'verbose_name': 'Pose Data',
                'verbose_name_plural': 'Pose Data',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=10)),
                ('gesture', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('landmarks', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_data', to='bodyanalytics.movementrecord')),
            ],
            options={
                'verbose_name': 'Hand Data',
                'verbose_name_plural': 'Hand Data',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_openness_left', models.FloatField(blank=True, null=True)),
                ('eye_openness_right', models.FloatField(blank=True, null=True)),
                ('mouth_openness', models.FloatField(blank=True, null=True)),
                ('head_position_x', models.FloatField(blank=True, null=True)),
                ('head_position_y', models.FloatField(blank=True, null=True)),
                ('head_position_z', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='bodyanalytics.movementrecord')),
            ],
            options={
                'verbose_name': 'Face Data',
                'verbose_name_plural': 'Face Data',
                'ordering': ['created_at'],
            },
        ),
    ]
