# Generated by Django 4.2.7 on 2025-12-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversations',
            fields=[
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('conversation', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_conversations',
            },
        ),
        migrations.CreateModel(
            name='CompanyCalendars',
            fields=[
                ('is_available', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company_calendars',
            },
        ),
        migrations.CreateModel(
            name='CourseLessons',
            fields=[
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_service', models.BooleanField(blank=True, null=True)),
                ('lesson_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('content_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('animation_3d_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'course_lessons',
            },
        ),
        migrations.CreateModel(
            name='CourseModules',
            fields=[
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course_modules',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseTests',
            fields=[
                ('passing_score', models.IntegerField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.courses')),
            ],
            options={
                'db_table': 'course_tests',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('duration_hours', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_type_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='TrainingDomains',
            fields=[
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_count', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'training_domains',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('account_non_expired', models.BooleanField()),
                ('account_non_locked', models.BooleanField()),
                ('ccpa_accepted', models.BooleanField(blank=True, null=True)),
                ('commercial_use_consent', models.BooleanField(blank=True, null=True)),
                ('credentials_non_expired', models.BooleanField()),
                ('enabled', models.BooleanField()),
                ('is_blocked', models.BooleanField(blank=True, null=True)),
                ('rgpd_accepted', models.BooleanField(blank=True, null=True)),
                ('ccpa_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('commercial_use_consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rgpd_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTypeDefinitionBackup',
            fields=[
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('show_in_selection', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('description_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('bigger', models.CharField(max_length=255)),
                ('company_type', models.CharField(blank=True, max_length=255, null=True)),
                ('label_en', models.CharField(max_length=255)),
                ('label_fr', models.CharField(max_length=255)),
                ('type_code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'user_type_definition_backup',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('desc_en', models.CharField(blank=True, max_length=500, null=True)),
                ('desc_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('bigger', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_types',
            },
        ),
        migrations.CreateModel(
            name='UserTestResults',
            fields=[
                ('passed', models.BooleanField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.coursetests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'user_test_results',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.usertypes'),
        ),
        migrations.CreateModel(
            name='UserOffers',
            fields=[
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(max_length=255)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.offers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'user_offers',
            },
        ),
        migrations.CreateModel(
            name='UserModuleCompletions',
            fields=[
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.coursemodules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'user_module_completions',
            },
        ),
        migrations.CreateModel(
            name='UserLessonCompletions',
            fields=[
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.courselessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'user_lesson_completions',
            },
        ),
        migrations.CreateModel(
            name='UserCourseCompletions',
            fields=[
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'user_course_completions',
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('blacklisted_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'token_blacklist',
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('points', models.IntegerField(blank=True, null=True)),
                ('question_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('question_text', models.CharField(max_length=1000)),
                ('expected_answer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('question_type', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.courselessons')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.coursetests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'test_questions',
            },
        ),
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('answer_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_correct', models.CharField(blank=True, max_length=255, null=True)),
                ('is_logical', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.testquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'test_answers',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('is_open_to_all', models.BooleanField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('service_type', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicerequests_recipient_set', to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'service_requests',
            },
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('completed', models.BooleanField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.courses')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'registrations',
            },
        ),
        migrations.CreateModel(
            name='RefreshTokens',
            fields=[
                ('revoked', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetTokens',
            fields=[
                ('is_used', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='MeetingRequests',
            fields=[
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proposed_end_time', models.DateTimeField(blank=True, null=True)),
                ('proposed_start_time', models.DateTimeField(blank=True, null=True)),
                ('requested_end_time', models.DateTimeField()),
                ('requested_start_time', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('company_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.companycalendars')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingrequests_requester_set', to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'meeting_requests',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('approved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('test_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.testanswers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
                ('user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.usertypes')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('movement_detected', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.AddField(
            model_name='coursemodules',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.courses'),
        ),
        migrations.AddField(
            model_name='courselessons',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users'),
        ),
        migrations.AddField(
            model_name='companycalendars',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users'),
        ),
        migrations.CreateModel(
            name='UserDomainCompletions',
            fields=[
                ('is_free_access', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_link', models.CharField(blank=True, max_length=500, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.trainingdomains')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyanalytics.users')),
            ],
            options={
                'db_table': 'user_domain_completions',
                'unique_together': {('user', 'domain')},
            },
        ),
    ]
