# Generated by Django 4.2.7 on 2025-12-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyanalytics', '0002_offer_useroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringBootUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('account_non_expired', models.BooleanField(default=True)),
                ('account_non_locked', models.BooleanField(default=True)),
                ('credentials_non_expired', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('rgpd_accepted', models.BooleanField(default=False)),
                ('rgpd_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ccpa_accepted', models.BooleanField(default=False)),
                ('ccpa_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('commercial_use_consent', models.BooleanField(default=False)),
                ('commercial_use_consent_at', models.DateTimeField(blank=True, null=True)),
                ('user_type_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Spring Boot User',
                'verbose_name_plural': 'Spring Boot Users',
                'db_table': 'users',
            },
        ),
        migrations.AlterUniqueTogether(
            name='useroffer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useroffer',
            name='offer_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroffer',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='duration_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user_type_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='offer',
            table='offers',
        ),
        migrations.AlterModelTable(
            name='useroffer',
            table='user_offers',
        ),
        migrations.RemoveField(
            model_name='useroffer',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='useroffer',
            name='user',
        ),
    ]
